version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    env_file: .env
    ports:
      - "3308:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    command: --default-authentication-plugin=mysql_native_password
